# Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
import plotly.express as px

# Read in ESPN predictions

In [3]:
espn_file = r"C:\Users\mrjay\python\jupyter_notebooks\Projects\brownlow\data\espn_historical_predictions.xlsx"
espn_2024 = pd.read_excel(espn_file, sheet_name="espn_2024")
espn_2023 = pd.read_excel(espn_file, sheet_name="espn_2023")
espn_2022 = pd.read_excel(espn_file, sheet_name="espn_2022")
espn_2021 = pd.read_excel(espn_file, sheet_name="espn_2021")

In [4]:
espn_2024 = espn_2024.assign(SEASON = 2024)
espn_2023 = espn_2023.assign(SEASON = 2023)
espn_2022 = espn_2022.assign(SEASON = 2022)
espn_2021 = espn_2021.assign(SEASON = 2021)

In [5]:
espn_historical = [espn_2021, espn_2022, espn_2023, espn_2024]

In [6]:
def norm_cols(df):
    df.columns = df.columns.str.upper() # capitalize
    df.columns = df.columns.str.replace(' ','_')
    df.columns = df.columns.str.replace('.','_')
    return df

In [7]:
# normalize columns
espn_historical = [norm_cols(f) for f in espn_historical]

In [8]:
# combine list of DF to one single DF
espn_historical_df = pd.concat(espn_historical)

## Read in Brownlow Results

In [9]:
brownlow_file = r"c:\Users\mrjay\python\jupyter_notebooks\Projects\brownlow\data\brownlow_stats_2018_2024_fitzroy.csv"

In [10]:
brownlow = pd.read_csv(brownlow_file, 
                       usecols=['Brownlow.Votes','First.name','Surname', 'Season','Round','Playing.for','Away.team'])

C:\Users\mrjay\AppData\Local\Temp\ipykernel_25784\2109441108.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  brownlow = pd.read_csv(brownlow_file,

In [11]:
# normalize columns
brownlow = norm_cols(brownlow)

In [12]:
# filter as we only care about votes
brownlow = brownlow[brownlow['BROWNLOW_VOTES'] > 0]

In [13]:
# convert to integer
brownlow['ROUND'] = brownlow['ROUND'].astype('int')

In [14]:
# add player col to join on
brownlow = brownlow.assign(PLAYER = lambda x: (x['FIRST_NAME'] + " " + x['SURNAME']).str.upper())

In [15]:
brownlow.sample(n=5)

,SEASON,ROUND,FIRST_NAME,SURNAME,PLAYING_FOR,BROWNLOW_VOTES,AWAY_TEAM,PLAYER
42976,2020,11,Nat,Fyfe,Fremantle,2.0,Hawthorn,NAT FYFE
10810,2023,3,Taylor,Adams,Collingwood,3.0,Richmond,TAYLOR ADAMS
401,2024,2,Rowan,Marshall,St Kilda,3.0,St Kilda,ROWAN MARSHALL
27852,2022,21,Lachie,Whitfield,Greater Western Sydney,2.0,Essendon,LACHIE WHITFIELD
10354,2023,2,Charlie,Curnow,Carlton,2.0,Geelong,CHARLIE CURNOW

In [16]:
espn_historical_df.sample(n=3)

,VOTES,PLAYER,TEAM,TAB_ODDS,R1,R2,R3,R4,R5,R6,...,R17,R18,R19,R20,R21,R22,R23,SEASON,R24,OR
27,13.5,TOM LIBERATORE,WB,NaN,-,-,-,-,-,-,...,-,1,2.5,-,2,-,-,2023,1.5,NaN
7,20.0,CONNOR ROZEE,PA,126.0,-,-,-,-,-,2.5,...,3,-,-,3,-,-,3,2022,NaN,NaN
40,10.0,TOM STEWART,GEE,NaN,-,3,1,-,-,-,...,1.5,-,-,2.5,2,-,-,2024,-,-

# Compare names

In [17]:
brownlow_player_list = sorted(brownlow['PLAYER'].unique().tolist())

In [18]:
espn_player_list = sorted(espn_historical_df['PLAYER'].unique().tolist())

In [19]:
# not empty because many players poll at brownlow!
set(brownlow_player_list) - set(espn_player_list)

{'AARON HALL',
 'AARON NAUGHTON',
 'AARON SANDILANDS',
 'AARON YOUNG',
 'ADAM SAAD',
 'ALEC WATERMAN',
 'ALEX DAVIES',
 'ALEX KEATH',
 'ALEX NEAL-BULLEN',
 'ALEX PEARCE',
 'ALEX SEXTON',
 'ALEX WITHERDEN',
 'ALIIR ALIIR',
 'ANDREW GAFF',
 'ANDREW MCGRATH',
 'ANDREW PHILLIPS',
 'ANGUS BRAYSHAW',
 'ANTHONY MCDONALD-TIPUNGWUTI',
 'ARCHIE PERKINS',
 'BACHAR HOULI',
 'BAILEY BANFIELD',
 'BAILEY DALE',
 'BAILEY SCOTT',
 'BAILEY SMITH',
 'BAILEY WILLIAMS',
 'BAYLEY FRITSCH',
 'BEAU MCCREERY',
 'BEN AINSWORTH',
 'BEN BROWN',
 'BEN JACOBS',
 'BEN KING',
 'BEN LONG',
 'BEN MCEVOY',
 'BEN RONKE',
 'BILLY GOWERS',
 'BLAKE ACRES',
 'BLAKE HARDWICK',
 'BRAD CLOSE',
 'BRAD EBERT',
 'BRAD SHEPPARD',
 'BRADLEY HILL',
 'BRANDAN PARFITT',
 'BRANDON ELLIS',
 'BRAYDEN FIORINI',
 'BRAYDEN MAYNARD',
 'BRENDON AH CHEE',
 'BRENDON GODDARD',
 'BRENNAN COX',
 'BRENT DANIELS',
 'BRETT DELEDIO',
 'BRODIE GRUNDY',
 'BRODIE SMITH',
 'BRODY MIHOCEK',
 'BRYCE GIBBS',
 'CALE HOOKER',
 'CALEB DANIEL',
 'CALLAN WARD',
 'CALLUM BROWN',
 'CALLUM COLEMAN-JONES',
 'CALLUM SINCLAIR',
 'CALLUM WILKIE',
 'CAM ELLIS-YOLMEN',
 'CAM MCCARTHY',
 'CAM RAYNER',
 'CAMERON GUTHRIE',
 'CAMERON ZURHAAR',
 'CHAD WINGARD',
 'CHANGKUOTH JIATH',
 'CHARLIE BALLARD',
 'CHARLIE CAMERON',
 'CHARLIE DIXON',
 'CHRIS MASTEN',
 'CODY WEIGHTMAN',
 'COLBY MCKERCHER',
 'CONNOR BLAKELY',
 'CONNOR BUDARICK',
 'CONNOR IDUN',
 'CONNOR MACDONALD',
 'CONOR NASH',
 'COOPER SHARMAN',
 'DAN BUTLER',
 'DAN HANNEBERY',
 'DAN HOUSTON',
 'DANE RAMPE',
 'DANIEL MCSTAY',
 'DANIEL MENZEL',
 'DANIEL RICH',
 'DANIEL RIOLI',
 'DARCY BYRNE-JONES',
 'DARCY CAMERON',
 'DARCY FOGARTY',
 'DARCY JONES',
 'DARCY MOORE',
 'DARCY TUCKER',
 'DAVID ARMITAGE',
 'DAVID ASTBURY',
 'DAVID CUNINGHAM',
 'DAVID MYERS',
 'DAVID SWALLOW',
 'DAVID ZAHARAKIS',
 'DAWSON SIMPSON',
 'DAYNE BEAMS',
 'DEREK EGGMOLESSE-SMITH',
 'DEVON SMITH',
 'DYLAN GRIMES',
 'DYLAN SHIEL',
 'DYSON HEPPELL',
 'EASTON WOOD',
 'ED CURNOW',
 'ED LANGDON',
 'EDDIE BETTS',
 'ELIJAH HOLLANDS',
 'ERIC HIPWOOD',
 'FINN CALLAGHAN',
 'GARY ABLETT',
 'GARY ROHAN',
 'GEORGE HEWETT',
 'GEORGE WARDLAW',
 'GRYAN MIERS',
 'HAMISH HARTLETT',
 'HARLEY REID',
 'HARRIS ANDREWS',
 'HARRY HIMMELBERG',
 'HARRY MCKAY',
 'HARRY PERRYMAN',
 'HARRY PETTY',
 'HAYDEN MCLEAN',
 'HUGH GREENWOOD',
 'ISAAC CUMMING',
 'ISAAC QUAYNOR',
 'ISAAC SMITH',
 'JACK BILLINGS',
 'JACK BOWES',
 'JACK CRISP',
 'JACK DARLING',
 'JACK GINNIVAN',
 'JACK GRAHAM',
 'JACK GUNSTON',
 'JACK HAYES',
 'JACK HENRY',
 'JACK HIGGINS',
 'JACK LONIE',
 'JACK LUKOSIUS',
 'JACK MACRAE',
 'JACK MARTIN',
 'JACK NEWNES',
 'JACK PETRUCCELLE',
 'JACK REDDEN',
 'JACK SCRIMSHAW',
 'JACK SILVAGNI',
 'JACK STEVEN',
 'JACK WATTS',
 'JACK ZIEBELL',
 'JACOB KOSCHITZKE',
 'JACOB VAN ROOYEN',
 'JACOB WEITERING',
 'JADE GRESHAM',
 'JAEGER OMEARA',
 'JAIDYN STEPHENSON',
 'JAKE AARTS',
 'JAKE CARLISLE',
 'JAKE LEVER',
 'JAKE LLOYD',
 'JAKE MELKSHAM',
 'JAKE RICCARDI',
 'JAKE SOLIGO',
 'JAKE WATERMAN',
 'JAMAINE JONES',
 'JAMARRA UGLE-HAGAN',
 'JAMES AISH',
 'JAMES FRAWLEY',
 'JAMES HARMES',
 'JAMES PEATLING',
 'JAMES ROWBOTTOM',
 'JAMES SICILY',
 'JAMES WORPEL',
 'JAMIE CRIPPS',
 'JAMIE ELLIOTT',
 'JARED POLEC',
 'JARMAN IMPEY',
 'JARRAD MCVEIGH',
 'JARRAD WAITE',
 'JARROD BERRY',
 'JARROD HARBROW',
 'JARROD WITTS',
 'JARRYD ROUGHEAD',
 'JARRYN GEARY',
 'JASON CASTAGNA',
 'JASON JOHANNISEN',
 'JAYDEN SHORT',
 'JED ANDERSON',
 'JED BEWS',
 'JEFF GARLETT',
 'JEREMY FINLAYSON',
 'JEREMY MCGOVERN',
 'JEREMY SHARP',
 'JOE DANIHER',
 'JOEL AMARTEY',
 'JOEL HAMLING',
 'JOHN NOBLE',
 'JONATHON CEGLAR',
 'JORDAN CLARK',
 'JORDAN RIDLEY',
 'JOSH BRUCE',
 'JOSH CADDY',
 'JOSH CORBETT',
 'JOSH DRAPER',
 'JOSH JENKINS',
 'JOSH KENNEDY',
 'JOSH RACHELE',
 'JOSH SCHACHE',
 'JOSH THOMAS',
 'JOSH TREACY',
 'JOSH WEDDLE',
 'JUDD MCVEE',
 'JUSTIN MCINERNEY',
 'JUSTIN WESTHOFF',
 'JYE AMISS',
 'KADE CHANDLER',
 'KADE SIMPSON',
 'KAI LOHMANN',
 'KANE FARRELL',
 'KANE LAMBERT',
 'KEIDEAN COLEMAN',
 'KIEREN BRIGGS',
 'KYLE LANGFORD',
 'KYSAIAH PICKETT',
 'LACHIE HENDERSON',
 'LACHIE HUNTER',
 'LACHIE SCHULTZ',
 'LACHIE WELLER',
 'LACHLAN BRAMBLE',
 'LACHLAN SHOLL',
 'LEVI CASBOULT',
 'LIAM BAKER',
 'LIAM DUGGAN',
 'LIAM HENRY',
 'LIAM JONES',
 'LIAM RYAN',
 'LIAM SHIELS',
 'LINCOLN MCCARTHY',
 'LOGAN MCDONALD',
 'LUKE BREUST',
 'LUKE MCDONALD',
 'LUKE RYAN',
 'LUKE SHUEY',
 'MABIOR CHOL',
 'MARC MURPHY',
 'MARCUS WINDHAGER',
 'MARK BLICAVS',
 'MARK OCONNOR',
 'MARLEY WILLIAMS',
 'MARLION PICKETT',
 'MARTY HORE',
 'MASON COX',
 'MASON REDMAN',
 'MASON WOOD',
 'MASSIMO DAMBROSIO',
 'MATT CROUCH',
 'MATT DE BOER',
 'MATT ROBERTS',
 'MATT SCHARENBERG',
 'MATT SUCKLING',
 'MATTAES PHILLIPOU',
 'MATTHEW KENNEDY',
 'MATTHEW KREUZER',
 'MATTHEW TABERNER',
 'MAX KING',
 'MICHAEL GIBBONS',
 'MICHAEL HIBBERD',
 'MICHAEL HURLEY',
 'MICHAEL WALTERS',
 'MITCH BROWN',
 'MITCH DUNCAN',
 'MITCH GEORGIADES',
 'MITCH LEWIS',
 'MITCH MCGOVERN',
 'MITCH ROBINSON',
 'MITCH WALLIS',
 'NASIAH WANGANEEN-MILERA',
 'NATHAN BROAD',
 'NATHAN JONES',
 'NATHAN MURPHY',
 'NIC NAITANUI',
 'NIC NEWMAN',
 'NICK BLAKEY',
 'NICK HAYNES',
 'NICK HIND',
 'NICK LARKEY',
 'NICK VLASTUIN',
 'NOAH BALTA',
 'OLIVER DEMPSEY',
 'OLIVER FLORENT',
 'OLIVER HENRY',
 'ORAZIO FANTASIA',
 'OSCAR ALLEN',
 'OSCAR MCINERNEY',
 'PADDY DOW',
 'PADDY RYDER',
 'PATRICK LIPINSKI',
 'PAUL AHERN',
 'PAUL PUOPOLO',
 'PAUL SEEDSMAN',
 'PETER LADHAMS',
 'PETER WRIGHT',
 'PHIL DAVIS',
 'QUINTON NARKLE',
 'REECE CONCA',
 'REILLY OBRIEN',
 'RHYS MATHIESON',
 'RICHARD DOUGLAS',
 'RICKY HENDERSON',
 'RILEY BONNER',
 'RILEY THILTHORPE',
 'ROBBIE GRAY',
 'ROBBIE TARRANT',
 'RORY ATKINS',
 'RORY LOBB',
 'RORY SLOANE',
 'RYAN CLARKE',
 'RYAN GRIFFEN',
 'RYLEY SANDERS',
 'SAM BERRY',
 'SAM COLLINS',
 'SAM DARCY',
 'SAM DAY',
 'SAM DOCHERTY',
 'SAM DRAPER',
 'SAM DURHAM',
 'SAM FROST',
 'SAM GRAY',
 'SAM JACOBS',
 'SAM MENEGOLA',
 'SAM PETREVSKI-SETON',
 'SAM POWELL-PEPPER',
 'SAM REID',
 'SAM SWITKOWSKI',
 'SAM TAYLOR',
 'SCOTT LYCETT',
 'SCOTT PENDLEBURY',
 'SCOTT THOMPSON',
 'SEBASTIAN ROSS',
 'SHANE EDWARDS',
 'SHANNON HURN',
 'SHAUN BURGOYNE',
 'SHAUN GRIGG',
 'SHAUN HIGGINS',
 'SHAUN MCKERNAN',
 'STEELE SIDEBOTTOM',
 'STEFAN MARTIN',
 'STEVEN MAY',
 'STEVEN MOTLOP',
 'TANNER BRUHN',
 'TARRYN THOMAS',
 'TIM ENGLISH',
 'TIM MEMBREY',
 'TIM OBRIEN',
 'TOBY BEDFORD',
 'TOBY MCLEAN',
 'TOBY NANKERVIS',
 'TODD GOLDSTEIN',
 'TODD MARSHALL',
 'TOM ATKINS',
 'TOM BARRASS',
 'TOM BELLCHAMBERS',
 'TOM CLUREY',
 'TOM CUTLER',
 'TOM DE KONING',
 'TOM HICKEY',
 'TOM JONAS',
 'TOM LANGDON',
 'TOM LYNCH',
 'TOM MCCARTIN',
 'TOM MCDONALD',
 'TOM PAPLEY',
 'TOM PHILLIPS',
 'TOM ROCKLIFF',
 'TOM SCULLY',
 'TRENT COTCHIN',
 'TRENT DUMONT',
 'TRENT RIVERS',
 'TRISTAN XERRI',
 'TYSON STENGLE',
 'WAYNE MILERA',
 'WILL ASHCROFT',
 'WILL DAY',
 'WILL HAYWARD',
 'WILL HOSKIN-ELLIOTT',
 'WILL PHILLIPS',
 'WILL SETTERFIELD',
 'WILLIE RIOLI',
 'ZAC BAILEY',
 'ZAC FISHER',
 'ZAC WILLIAMS',
 'ZACH GUTHRIE',
 'ZACH TUOHY',
 'ZAK JONES'}

In [20]:
# this is empty so all players ESPN nominated are in the Brownlow records
set(espn_player_list) - set(brownlow_player_list)

{'CAM GUTHRIE', 'JACKSON MACRAE', "JAEGER O'MEARA"}

# What is story with OR Opening round?

In [21]:
espn_historical_df.query("OR != 0 & OR.notna()")

,VOTES,PLAYER,TEAM,TAB_ODDS,R1,R2,R3,R4,R5,R6,...,R17,R18,R19,R20,R21,R22,R23,SEASON,R24,OR
0,34.0,PATRICK CRIPPS,CARL,NaN,2,-,2,1.5,-,3,...,1,2,2,-,2,-,2.5,2024,1.5,2
1,32.5,NICK DAICOS,COLL,NaN,1,-,-,-,-,1,...,-,-,-,3,2,-,2.5,2024,3,1
2,29.0,LACHIE NEALE,BRIS,NaN,-,-,3,0.5,-,-,...,3,3,-,2,2.5,-,1,2024,3,-
3,28.5,ISAAC HEENEY,SYD,NaN,2.5,2.5,1.5,3,-,1,...,0.5,-,-,-,-,3,2.5,2024,-,2.5
4,28.0,MARCUS BONTEMPELLI,WB,NaN,-,3,2.5,2,-,-,...,-,0.5,-,1.5,3,1,1,2024,1,-
5,23.5,CALEB SERONG,FRE,NaN,3,2,-,-,2,-,...,-,0.5,2.5,2.5,-,2,-,2024,-,-
6,23.5,ERROL GULDEN,SYD,NaN,-,-,-,2,-,2,...,-,3,2.5,-,-,-,0.5,2024,3,-
7,23.0,TOM GREEN,GWS,NaN,2.5,3,-,-,-,-,...,0.5,1.5,1.5,2,1,1,1,2024,1,2
8,22.5,ZACH MERRETT,ESS,NaN,1,0.5,1.5,1,1,0.5,...,3,-,2,-,-,-,-,2024,2,-
9,21.5,NOAH ANDERSON,GC,NaN,1,-,-,1.5,3,-,...,-,2.5,-,-,-,-,-,2024,1.5,1
10,19.5,ZAK BUTTERS,PA,NaN,2,3,-,-,1,1,...,2,1,-,-,-,1,3,2024,-,-
11,19.5,ADAM TRELOAR,WB,NaN,-,-,2.5,-,-,2,...,-,-,3,3,1.5,-,0.5,2024,-,-
12,19.5,CHAD WARNER,SYD,NaN,2.5,0.5,-,-,-,-,...,-,2,-,-,-,2,-,2024,1,-
13,19.5,JASON HORNE-FRANCIS,PA,NaN,1,-,-,2,-,-,...,-,-,-,1,1,3,2,2024,2,-
14,18.0,JORDAN DAWSON,ADE,NaN,-,0.5,-,1.5,-,3,...,-,2,-,-,-,2,-,2024,-,-
15,17.5,ROWAN MARSHALL,STK,NaN,0.5,-,-,0.5,2.5,-,...,-,1,-,2,-,2.5,1.5,2024,-,-
16,17.5,ANDREW BRAYSHAW,FRE,NaN,0.5,0.5,-,2,-,-,...,2.5,1,2,2.5,1.5,-,0.5,2024,2,-
17,17.0,MATT ROWELL,GC,NaN,2.5,-,-,-,1,-,...,-,-,-,-,2,3,-,2024,-,3
18,17.0,HUGH MCCLUGGAGE,BRIS,NaN,-,-,-,2.5,1,-,...,-,1,2.5,-,1.5,-,0.5,2024,0.5,-
19,17.0,JAI NEWCOMBE,HAW,NaN,-,-,-,-,-,2.5,...,-,-,-,2,-,-,3,2024,3,-
20,16.0,MAX GAWN,MEL,NaN,2,-,2,-,1.5,-,...,-,-,-,-,1.5,-,-,2024,-,-
21,16.0,HAYDEN YOUNG,FRE,NaN,-,-,3,-,-,-,...,1,-,0.5,0.5,2,-,-,2024,-,-
22,15.5,LUKE DAVIES-UNIACKE,NM,NaN,-,1,-,-,-,-,...,1.5,-,0.5,-,3,-,-,2024,-,-
23,15.0,CONNOR ROZEE,PA,NaN,3,1,-,3,2,-,...,2.5,-,2.5,-,-,-,1,2024,-,-
24,15.0,OLLIE WINES,PA,NaN,-,-,-,-,-,-,...,0.5,-,1,2.5,2,-,-,2024,2,-
25,14.5,SAM WALSH,CARL,NaN,-,-,-,-,3,2,...,-,-,-,-,-,-,-,2024,-,-
26,14.5,HARRY SHEEZEL,NM,NaN,-,-,-,-,0.5,-,...,3,-,3,2.5,-,2,-,2024,-,-
27,14.0,JEREMY CAMERON,GEE,NaN,-,-,-,-,3,-,...,2.5,-,-,0.5,3,-,-,2024,3,-
28,13.5,NIC MARTIN,ESS,NaN,-,-,2.5,-,-,2,...,-,3,-,-,-,1.5,2.5,2024,-,-
29,13.0,JESSE HOGAN,GWS,NaN,2.5,-,-,-,-,-,...,2.5,-,0.5,-,3,1,2.5,2024,-,-
30,13.0,SAM FLANDERS,GC,NaN,1,-,-,-,1,-,...,-,1.5,0.5,-,-,-,-,2024,2.5,1
31,13.0,LACHIE WHITFIELD,GWS,NaN,-,1,-,-,1,-,...,-,1.5,2.5,1,0.5,-,-,2024,1,-
32,12.5,DYLAN MOORE,HAW,NaN,-,-,-,-,-,1,...,-,-,0.5,-,-,3,0.5,2024,1.5,-
33,12.0,CHRISTIAN PETRACCA,MEL,NaN,2,3,-,3,-,-,...,-,-,-,-,-,-,-,2024,-,-
34,12.0,DAYNE ZORKO,BRIS,NaN,-,-,-,-,-,1.5,...,-,-,-,3,-,-,-,2024,-,-
35,12.0,JACK SINCLAIR,STK,NaN,-,-,-,-,-,-,...,-,-,1.5,-,-,1.5,-,2024,2,-
36,11.5,MAX HOLMES,GEE,NaN,2,-,-,-,2,2,...,-,0.5,-,-,-,-,-,2024,1,-
37,11.0,JYE CALDWELL,ESS,NaN,-,-,-,-,1.5,-,...,1,-,-,-,1.5,-,-,2024,-,-
38,10.0,IZAK RANKINE,ADE,NaN,-,-,-,-,2,-,...,-,-,-,-,-,-,-,2024,-,-
39,10.0,ELLIOT YEO,WCE,NaN,-,-,-,0.5,2,2.5,...,-,1,-,-,2,-,-,2024,-,-
40,10.0,TOM STEWART,GEE,NaN,-,3,1,-,-,-,...,1.5,-,-,2.5,2,-,-,2024,-,-
41,10.0,JACK STEELE,STK,NaN,-,1,-,3,-,-,...,0.5,-,0.5,2,-,-,2,2024,-,-
42,10.0,ED RICHARDS,WB,NaN,-,-,-,-,-,-,...,-,-,2,1,-,-,-,2024,3,-

In [22]:
brownlow

,SEASON,ROUND,FIRST_NAME,SURNAME,PLAYING_FOR,BROWNLOW_VOTES,AWAY_TEAM,PLAYER
1,2024,1,Nick,Blakey,Sydney,1.0,Melbourne,NICK BLAKEY
21,2024,1,Chad,Warner,Sydney,3.0,Melbourne,CHAD WARNER
44,2024,1,Jack,Viney,Melbourne,2.0,Melbourne,JACK VINEY
47,2024,1,Harris,Andrews,Brisbane Lions,1.0,Carlton,HARRIS ANDREWS
76,2024,1,Charlie,Curnow,Carlton,2.0,Carlton,CHARLIE CURNOW
...,...,...,...,...,...,...,...,...
63779,2018,23,Max,Gawn,Melbourne,2.0,Greater Western Sydney,MAX GAWN
63801,2018,23,Stephen,Coniglio,Greater Western Sydney,1.0,Greater Western Sydney,STEPHEN CONIGLIO
63839,2018,23,Jack,Steele,St Kilda,1.0,North Melbourne,JACK STEELE
63840,2018,23,Jack,Steven,St Kilda,3.0,North Melbourne,JACK STEVEN
63850,2018,23,Todd,Goldstein,North Melbourne,2.0,North Melbourne,TODD GOLDSTEIN

In [23]:
brownlow.query("SEASON == 2024 & PLAYER == 'PATRICK CRIPPS' ")

,SEASON,ROUND,FIRST_NAME,SURNAME,PLAYING_FOR,BROWNLOW_VOTES,AWAY_TEAM,PLAYER
189,2024,2,Patrick,Cripps,Carlton,3.0,Richmond,PATRICK CRIPPS
1040,2024,4,Patrick,Cripps,Carlton,3.0,Carlton,PATRICK CRIPPS
1546,2024,5,Patrick,Cripps,Carlton,2.0,Carlton,PATRICK CRIPPS
2259,2024,7,Patrick,Cripps,Carlton,3.0,Greater Western Sydney,PATRICK CRIPPS
2743,2024,8,Patrick,Cripps,Carlton,2.0,Carlton,PATRICK CRIPPS
3318,2024,10,Patrick,Cripps,Carlton,3.0,Melbourne,PATRICK CRIPPS
4237,2024,12,Patrick,Cripps,Carlton,3.0,Gold Coast,PATRICK CRIPPS
4582,2024,13,Patrick,Cripps,Carlton,3.0,Carlton,PATRICK CRIPPS
5180,2024,14,Patrick,Cripps,Carlton,2.0,Carlton,PATRICK CRIPPS
5524,2024,16,Patrick,Cripps,Carlton,3.0,Geelong,PATRICK CRIPPS
6146,2024,17,Patrick,Cripps,Carlton,3.0,Carlton,PATRICK CRIPPS
6423,2024,18,Patrick,Cripps,Carlton,1.0,Carlton,PATRICK CRIPPS
6791,2024,19,Patrick,Cripps,Carlton,2.0,Carlton,PATRICK CRIPPS
7412,2024,20,Patrick,Cripps,Carlton,3.0,North Melbourne,PATRICK CRIPPS
8124,2024,22,Patrick,Cripps,Carlton,3.0,Carlton,PATRICK CRIPPS
9090,2024,24,Patrick,Cripps,Carlton,3.0,Carlton,PATRICK CRIPPS
9435,2024,25,Patrick,Cripps,Carlton,3.0,St Kilda,PATRICK CRIPPS

In [24]:
brownlow['ROUND'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [25]:
brownlow.groupby(['SEASON'])['ROUND'].max()

SEASON
2018    23
2019    23
2020    18
2021    23
2022    23
2023    24
2024    25
Name: ROUND, dtype: int32